# Generated by Django 4.1 on 2022-08-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('E_Comm_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=None),
        ),
    ]
