# Generated by Django 4.1 on 2022-08-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('E_Comm_User', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('add', 'admin'), ('update', 'admin')], default=1,
                                   max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=9950124864, max_length=200, unique=True),
        ),
    ]
