# Generated by Django 4.1 on 2022-08-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('E_Comm_User', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='abhijeet', max_length=200)),
                ('first_name', models.CharField(default='Abhijeet', max_length=200)),
                ('last_name', models.CharField(default='Kumar', max_length=200)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('add', 'add'), ('update', 'update')], default=1,
                                          max_length=20)),
                ('phone', models.CharField(default=9950124864, max_length=200, unique=True)),
                ('email', models.CharField(default='MI01071997GMAIL.COM', max_length=32)),
            ],
        ),
    ]
