# Generated by Django 4.1 on 2022-08-20 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('E_Comm_User', '0008_user_password_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
