# Generated by Django 4.1 on 2022-08-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('E_Comm_User', '0009_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=30),
        ),
    ]
