# Generated by Django 4.1 on 2022-08-21 06:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('E_Comm_User', '0010_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
