# Generated by Django 4.1 on 2022-08-21 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('E_Comm_User', '0011_delete_product_delete_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
