# Generated by Django 4.1 on 2022-08-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pr_discription',
        ),
        migrations.AddField(
            model_name='product',
            name='pr_description',
            field=models.TextField(default=None, help_text='Product Descriptions'),
        ),
        migrations.AlterField(
            model_name='product',
            name='act_price',
            field=models.CharField(help_text='Actual Price', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='disc_price',
            field=models.IntegerField(default=0, help_text='Discounted Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_colour',
            field=models.CharField(help_text='Colour', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_fabric',
            field=models.CharField(help_text='Fabric', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_name',
            field=models.CharField(help_text='Product Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_size',
            field=models.ForeignKey(help_text='Size of Product', on_delete=django.db.models.deletion.CASCADE,
                                    to='Inventory.size'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_name',
            field=models.CharField(help_text='Size (XL/L/M/S/XS)', max_length=200),
        ),
    ]
