# Generated by Django 4.1 on 2022-08-21 09:10

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Inventory', '0002_remove_product_pr_discription_product_pr_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='placement_title'),
        ),
    ]
