# Generated by Django 4.1 on 2022-08-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Inventory', '0006_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_status',
            field=models.BooleanField(default=False),
        ),
    ]
