# Generated by Django 4.1 on 2022-08-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_phonemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='phoneModel',
        ),
    ]
